### PR TITLE
New build files.

### PR DESCRIPTION
**Pull request by mattwaler**
## Proposed changes

Running the build command of the most recent changes to the source files, allowing for other repos like postcss-purgecss to have the most up-to-date build.

## Types of changes

What types of changes does your code introduce to Purgecss?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

I made 0 changes to the source, just forked, ran the build, and created the PR. I think this may have been missed after merging the PR which fixed issues I am experiencing. [Ensure classes beginning with numbers are properly purged #185](https://github.com/FullHuman/purgecss/pull/185)

I opened an issue as well [here](https://github.com/FullHuman/postcss-purgecss/issues/34)

### CODE REVIEW

**Comment by benface** [comment]
@Ffloriel Any chance you can look at this soon? :) No need to tag a new release, just having the latest build in the repo would allow us to use the patch by specifying `"purgecss": "github:FullHuman/purgecss#bc9f3b5b9d670832f0d1cca7bc7facfb253fb60b"` in `package.json`. Thank you very much!

**Comment by mattwaler** [comment]
@benface if you need to use this in the meantime, feel free to use my repos, I will be leaving them up until this is resolved and probably in the future for stability.

`yarn add -D https://github.com/mattwaler/postcss-purgecss`
(if you're just using purge, updated purgecss dependency to point to repo below with new build files)

`yarn add -D https://github.com/mattwaler/purgecss`
(if you need the new build source files for other repos)

**Comment by mattwaler** [comment]
Is this merge ever going to happen? Still using my personal forks to get this working.

**Comment by Ffloriel** [comment]
I'm away right now, will be back in September :)
I'll merge this PR now

**Comment by mattwaler** [comment]
@benface @hacknug,

This is now fixed in the default package. I have updated safely to `@fullhuman/postcss-purgecss@1.3.0`. I will be removing my git repos today.

Just wanted to give you both a heads up.

**Comment by benface** [comment]
Thanks @mattwaler :)

**Comment by hacknug** [comment]
Thanks for the heads up!

**Pull request merged**
