### PR TITLE
Allows preserving children from whitelistPatterns

### PR DESCRIPTION
**Pull request by cmizzi**
## Proposed changes

Related to #39

## Types of changes

- [x] Add ability to provide a `whitelistPatterns` object instead of `RegExp` in order to resolve a `keepChildren` option to preserve `left to right` reader

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Assert `Flow` is working as well
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Ffloriel** [comment]
Thanks for the PR.
I think it's important to discuss about the API itself.
From the PR, if I understand correctly, someone would whitelist patterns the following way:
```
whitelistPatterns: [
                {
                    pattern: /^double-class$/,
                    keepChildren: true
                }
            ]
```
I think it would be better to have a different property for whitelist patterns.
The list of patterns can be long depending on the use cases and it could be easier to configure with a different property:

```
whitelistPatterns: [
                {
                    pattern: /^double-class$/,
                    keepChildren: true
                },
{
                    pattern: /^double-class$/,
                    keepChildren: true
                },
{
                    pattern: /^double-class$/,
                    keepChildren: true
                },
{
                    pattern: /^double-class$/,
                    keepChildren: true
                },
            ]
```
vs
```

```

**Comment by cmizzi** [comment]
Great idea. But, what happen if both contain same value ? We need a priority manager. First, we should manage `whitelistPatternsChildren` if fails, tests with `whitelistPatterns`

**Comment by Ffloriel** [comment]
In my opinion, the priority should go to the most conservative option. WhitelistPattersChildren will conserve children selectors. If case of a misconfiguration, giving priority to this option will not remove wanted css and break the application style. 
So if both contain the same value, WhitelistPattersChildren will have the priority.

**Comment by cmizzi** [comment]
I've applied changes. Now, a `whitelistPatternsChildren` is defined and works as excepted

**Comment by Ffloriel** [comment]
Thanks for the PR. The option is now available with v0.21.0

**Comment by robertvrabel** [comment]
Thank you for this PR! Looking forward to trying it out :)

**Pull request merged**
